### ISSUE TITLE
请问你实验的分割效果即缺陷的IOU是多少？

### ISSUE THREAD

**Issue by DCC-lzhy** [zacario-li/Segmentation-based-deep-learning-approach-for-surface-defect-detection#5]
我按照论文里的操作，奇偶次训练30张瑕疵和非瑕疵，然后在验证集上22张瑕疵上评估，瑕疵的IOU就只有0.626%，这样的iou还能用作后面的决策网络吗

**Comment by zacario-li** [comment]
> 我按照论文里的操作，奇偶次训练30张瑕疵和非瑕疵，然后在验证集上22张瑕疵上评估，瑕疵的IOU就只有0.626%，这样的iou还能用作后面的决策网络吗

IoU 0.626%? 还是 62.6%?

**Comment by DCC-lzhy** [comment]
0.00626，而且是在epoch=0的时候。

**Comment by DCC-lzhy** [comment]
是0.00626，我降低了学习率为0.001，最后一层通道为1，用的sigmoid函数，用的bcewithlogitloss，还未加入weight，bs=2，opti=adam，loss还是在0.69附近，我再调节参数试试，这是论文和TensorFlow版本做的，我还没验证这样的(0,1)计算出的iou对不对，但loss就很不正常。不行，我后面就再改成softmax，再看看结果。

**Comment by zacario-li** [comment]
> 是0.00626，我降低了学习率为0.001，最后一层通道为1，用的sigmoid函数，用的bcewithlogitloss，还未加入weight，bs=2，opti=adam，loss还是在0.69附近，我再调节参数试试，这是论文和TensorFlow版本做的，我还没验证这样的(0,1)计算出的iou对不对，但loss就很不正常。不行，我后面就再改成softmax，再看看结果。

你不如先用Dice作为loss来训练，然后再用bce验证你的想法。

**Comment by DCC-lzhy** [comment]
我把论文名字在GitHub上搜，出来了7个repository了，我一个一个看看【偷笑】。

**Comment by DCC-lzhy** [comment]
已经解决了，64分的验证集上瑕疵类别的iou达到0.56+，后续的decision network在训练集和验证集都能precision=1，recall=1。事实证明，论文里的几个实验对照是真实的，训练分割网络时，ce比mse要好很多，奇偶次训练正负样本比单独训练正样本要强，证明负样本是必要的，且需要平衡。膨胀也是有用的。
后续再试下dice loss。
